[23/May/2017:15:10:00] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python3.5/dist-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/michael.jolin/Programming/survip-api/causepy/pages/api.py", line 18, in index
    'version': config.PACKAGE_VERSION
AttributeError: module 'causepy.config.setup' has no attribute 'PACKAGE_VERSION'
[23/May/2017:15:10:00] HTTP 
Request Headers:
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
  ACCEPT-ENCODING: gzip, deflate, sdch, br
  Remote-Addr: 127.0.0.1
  HOST: localhost:8080
  USER-AGENT: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
  CONNECTION: keep-alive
  COOKIE: SURVI-Prevention-API=e26531008ba15226129455c78e8e9b5d388e9acc
  ACCEPT-LANGUAGE: en-US,en;q=0.8,fr;q=0.6
  CACHE-CONTROL: max-age=0
  UPGRADE-INSECURE-REQUESTS: 1
[23/May/2017:15:19:15] HTTP 
Request Headers:
  COOKIE: SURVI-Prevention-API=7e1ff0f6c871a12e072582b758dc8608c283259d
  UPGRADE-INSECURE-REQUESTS: 1
  USER-AGENT: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
  ACCEPT-ENCODING: gzip, deflate, sdch, br
  HOST: localhost:8080
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
  CONNECTION: keep-alive
  Remote-Addr: 127.0.0.1
  ACCEPT-LANGUAGE: en-US,en;q=0.8,fr;q=0.6
[23/May/2017:15:19:15] HTTP 
Traceback (most recent call last):
  File "/home/michael.jolin/Programming/survip-api/causepy/pages/api.py", line 75, in call_method
    'name': self.name,
AttributeError: 'Api' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python3.5/dist-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/michael.jolin/Programming/survip-api/apirest/classes/url_for_address.py", line 32, in country
    return self.call_method('Country', self.get_argument(args, kwargs))
  File "/home/michael.jolin/Programming/survip-api/causepy/pages/api.py", line 89, in call_method
    'name': self.name,
AttributeError: 'Api' object has no attribute 'name'
